FORMAT: 1A

# look4
This is an api for use in look4 version 1 



<!-- below is an defineing stuff -->
[Coordinate]: x,y,floor_id 

<!-- end of defineing stuff -->

# Group Promotion
Describe an api that relate **Promotion**

## List of all promotion  [/promotion{?limit,offset,order,coordinate}]

### List all Promotion [GET]
เราควรจะเรียงมันยังไงดี เอาโปรอะไรขึ้นก่อน

+ Parameters

    + limit = `20` (optional, number) ... The maximum number of results to return.
    + offset = `20`  (optional, number) ... Offset of promotion list for load more perpose 
    + order = `DESC` (optional, string) ... Order of sorting can contain DESC ASC.
    + coordinate = `Null` (optional,JSON)  ... User coordination if he/she is in store.
        + floor_id = 0 (require,number) ... The floor id of current location.
        + x = (require,number) ... x coordinate of picture
        + y = (require,number) ... y coordinate of picture 
    
+ Response 200 (application/json)

        [
        {
          "id": 1,//promotion id 
          "name": "Kim ju restaurant",
          "detail" : "ฉลองเปิดร้าน ลด 20% ",
          "pinned" : true // true if the promotion are advertorial promotion 
          "stor_id":1,
          "percent": 20,
          "distance": "12m",
          "promotion_type": "dealnow",// @TODO conclude this 
          "photo_url":"http://www.asiatiquethailand.com/cms_directory/content/asiatique/pic/shop-logo/Kimju_Korean_201302212015122563.png"
        
        }, {
          "id": 2,//promotion id 
          "name": "Capri @ aisiatique",
          "detail" : "สั่งพิซซ่า ซื้อ 1 แถม 1 ",
          "stor_id":2,
          "percent": null,
          "distance": "6m",
          "promotion_type": "getcode" 
          "promotion_end_time": "2014-11-03T10:14:09+00:00",//@TODO conclude this 
          "photo_url":"http://www.foodinc.ca/clients/5196237510/logo.gif"
        },
        ]
        
        
## List of all promotion  [/promotion/{id}]
### List all Promotion [GET]
เปิดหน้าโปรโมชั่นอันใดอันหนึ่ง 
+ Parameters
    + id (required, number) ... id ของโปรโมชั่นนั้นๆ 
    
+ Response 200 (application/json)

        {
            "id": 1,//promotion id 
            "name": "Kim ju restaurant",
            "detail" : "ฉลองเปิดร้าน ลด 20% ",
            "pinned" : true // true if the promotion are advertorial promotion 
            "stor_id":1,
            "percent": 20,
            "distance": "12m",
            "promotion_type": "dealnow",// @TODO conclude this 
            "photo_url":
            [
                "http://www.asiatiquethailand.com/cms_directory/content/asiatique/pic/shop-logo/Kimju_Korean_201302212015122563.png",
                "http://www.asiatiquethailand.com/cms_directory/content/asiatique/pic/shop-logo/Kimju_Korean_201302212015122563.png",
                "http://www.asiatiquethailand.com/cms_directory/content/asiatique/pic/shop-logo/Kimju_Korean_201302212015122563.png",
                "http://www.asiatiquethailand.com/cms_directory/content/asiatique/pic/shop-logo/Kimju_Korean_201302212015122563.png"
            ]
        }
        
        
        
## Use promotion [/promotion/use/{promotion_id}]
### Use promotion [POST]
กดใช้โปรโมชั่น กดเสร็จจะได้คูปองโค้ดกลับมาเพื่อไปแสดงให้ร้านค้าดู 
+ Parameters
    + promotion_id (required, number) ... id ของโปรโมชั่นนั้นๆ 
    
+ Response 200 (application/json)

        {
            "coupon_code": "A12345",
            "coupon_valid_until": "2014-11-10T11:13:01+07:00"
        }
        
        
# Group Directory 

## Use promotion [/directory/{place_id}]
### Use promotion [GET]
กดใช้โปรโมชั่น กดเสร็จจะได้คูปองโค้ดกลับมาเพื่อไปแสดงให้ร้านค้าดู 
+ Parameters
    + place_id (required, number) ... id ของสถานที่นั้นๆ 
    
+ Response 200 (application/json)

        [
        {
            "directory_id":1,
            "directory_name_th":"สาธารณูปโภค",
            "directory_name_en":"Utility",
            "directory_icon":"matherial-coffee" //see describetion about matherial icon schema
        },
        ]
        
        

# Group search (also click )

# Group Shop & Item in shop (maybe vote comment)

# Group Friend 

# Group Me (include settings)







## Create a Promotion [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response ,
"icon"200 (application/json)directory_

    + :"matherial-coffee"Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204


